import os
import numpy as np

header = """// --- file generated by codegen/make_melody.py ---

//  data for inventio in a minor by J.S. Bach

const uint16_t midi_to_step[128] PROGMEM = {\n    
"""

def freq_from_note(note, key):
    return pow(2.0, note/12) * key

def step_from_freq(freq):
    sample_rate = 16129;
    return round((2**16) * freq / sample_rate)

def step_from_note(note, key):
    return step_from_freq(freq_from_note(note, key))


midi_notes = np.arange(128) - 69
key = 440.0

steps = [step_from_note(note, key) for note in midi_notes]

filename = "tables/midi.c"

os.makedirs(os.path.dirname(filename), exist_ok=True)
with open(filename, "w") as file:
    file.write(header)
    for count, value in enumerate(steps):
        file.write("{0}".format(value).rjust(5) + ", ")
        if np.mod(count, 8) == 7:
            file.write("\n    ")

    file.write("\n};\n\n")

